# Resource Group/Location
variable "location" {}
variable "application_type" {}
variable "resource_type" {}
variable "resource_group" {}
variable "subnet_id" {}
variable "name" {}
variable "username" {}
variable "size" {}
variable "public_ip_address_id" {}
